/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import DAOCODE.ClienteCode;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class Operacao extends javax.swing.JInternalFrame {

    /**
     * Creates new form Operacao
     */
    public Operacao() {
         super("Operação",
              false, //resizable
               true, //closable
              false, //maximizable
               true);//iconifiable  
        initComponents();
        btgroup.add(deposito);
        btgroup.add(saque);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        saque = new javax.swing.JRadioButton();
        deposito = new javax.swing.JRadioButton();
        efetuar = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        id_conta = new javax.swing.JTextField();
        agencia = new javax.swing.JTextField();
        valor = new javax.swing.JTextField();

        jLabel1.setText("ID Conta:");

        jLabel2.setText("Agencia:");

        jLabel3.setText("Valor:");

        saque.setText("Saque");

        deposito.setText("Deposito");

        efetuar.setText("Efetuar");
        efetuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarActionPerformed(evt);
            }
        });

        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(id_conta, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(agencia)
                        .addComponent(valor))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(saque))
                            .addComponent(efetuar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deposito))))
                .addGap(0, 63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id_conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saque)
                    .addComponent(deposito))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(efetuar)
                    .addComponent(cancel))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void efetuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarActionPerformed
        ClienteCode cCode = new ClienteCode();
        
        if(deposito.isSelected()){
            if(cCode.efetuaOperacao(id_conta.getText(),agencia.getText(),valor.getText(),"DEPOSITO")){
                JOptionPane.showMessageDialog(this,"Deposito efetuado!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"A conta não é corrente ou não existe!");
            }    
        }else if(saque.isSelected()){
            
            if(cCode.efetuaOperacao(id_conta.getText(),agencia.getText(),valor.getText(),"SAQUE")){
                JOptionPane.showMessageDialog(this,"Saque efetuado!");
                this.dispose();
            }else{
                JOptionPane.showConfirmDialog(this,"A conta não é corrente ou não existe!");
            }    
        }else 
            JOptionPane.showMessageDialog(this,"Selecione a operação!");
    }//GEN-LAST:event_efetuarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agencia;
    private javax.swing.ButtonGroup btgroup;
    private javax.swing.JButton cancel;
    private javax.swing.JRadioButton deposito;
    private javax.swing.JButton efetuar;
    private javax.swing.JTextField id_conta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton saque;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
